### PR TITLE
Limit details field to 4096 characters (closes #140).

### LINKED ISSUE #140: Continuous pasting of long comments in the comment area make the experiment and browser unresponsive
**[Affected versions]:**
-Firefox 52.0 and up
-Pulse v1.1 RC

**[Affected Platforms]:**
-All Windows
-All Mac
-All Linux

**[Prerequisites]:**
-Pulse v1.1 RC was previously installed on a clean profile.
-Have a random comment in notepad of about 300 lines. Select the comment and copy it.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to a http or https webpage.
3. Click on Pulse icon from the URL bar.
4. Give the page a rating in order to go to the next part of the survey.
5. Select an option for how that webpage is.
6. Click the "Optional comments.." area and keep Ctrl+V pressed.

**[Expected result]:**
- The comment characters are limited to a reasonable amount.

**[Actual result]:**
- After about 20-30 seconds of continuous pasting the comment, the experiment and browser become unresponsive.

### PR DESCRIPTION
**Pull request by chuckharmston**
screen shot 2017-03-30 at 10 28 48 am

screen shot 2017-03-30 at 10 26 22 am

### CODE REVIEW

File: src/webextension/survey/components/survey.jsx [hunk 1]
```diff
@@ -54,7 +56,11 @@ class Survey extends Component {
               component={ReasonField}
               validate={[ required ]}
             />
-            <Field name="details" component={DetailsField} />
+            <Field
+              name="details"
+              component={DetailsField}
+              validate={[ maxLength(5096) ]}
```
Comment (lmorchard) [inline src/webextension/survey/components/survey.jsx]: 5096 is a very specific number - any reason why? Or just 1000 better than 2^12?

**Review by lmorchard — APPROVED** [review]
Generated myself 5096 characters, entered the 5097th and the message appeared & submission disabled. Deleted it and the message went away & submission enabled. LGTM!

File: src/webextension/survey/components/survey.jsx (hunk 1 above)
Comment (chuckharmston) [reply src/webextension/survey/components/survey.jsx]: It was supposed to be 4096 😞.

I like round numbers.
