### PR TITLE
Store active tab before opening survey in new tab (closes #175).

### LINKED ISSUE #175: Ping counts seem incorrect.
[This query](https://sql.telemetry.mozilla.org/queries/4209#8377) illustrates that there are more `pulse-prompted` pings than all others combined, which should not happen. Per [metrics documentation](https://github.com/mozilla/pulse/blob/master/docs/metrics.md#lifecycle), a `pulse-prompted` ping should always be followed by one of `pulse-dismissed` or `pulse-loaded` (which should then be followed by `pulse-unloaded` or `pulse-submitted` ping). It's unclear whether this is a code or data problem.

Two asks:

- @harterrt would you mind giving me a confidence level that the data in redash is currently accurate?
- @SoftVision-PaulOiegas could you have your team try to reproduce a situation where the above-linked lifecycle is not respected in the latest release on production? This can be done by watching the browser console, ensuring that pings of each event are correctly logged, then checking about:telemetry to ensure that pings of each event are also submitted. If something is wrong, the `pulse-submitted` one would be my guess as to where the problem is.

Thanks!

### PR DESCRIPTION
**Pull request by chuckharmston**
Originally, I'd tried storing the active tab immediately before opening the survey from the prompt. It appears that there was a race condition here; sometimes the tab stored was actually the one _in_ which the survey was opened, rather than the one _from_ which it was opened. This caused the measurement process to silently fail. The good news: no bad data was reported. The bad news: in these cases, no good data was reported.

This patch moves the storage of the tab from `openSurvey` to the time the prompt is rendered, ensuring that there is no race condition. After it's merged, I'll release a new version.

In the process of debugging this, I made a nice refactor (moving message handling into a library) that I kept. Minimal new code, just some shifting.

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -1,15 +1,11 @@
 import { PageMod } from 'sdk/page-mod';
 import self from 'sdk/self';
-import { storage } from 'sdk/simple-storage';
 import webext from 'sdk/webextension';
-import tabs from 'sdk/tabs';
 import { getMostRecentBrowserWindow } from 'sdk/window/utils';
 
-import { e10sStatus, e10sProcessCount } from './lib/e10s-status';
 import Logger from './lib/log';
+import handleMessage from './lib/messages';
```
Comment (fzzzy) [inline src/index.js:7]: Why export handleMessage as default and another function from this module as a named export? Seems less confusing just to export handleMessage as a named export.

File: src/lib/messages.js [hunk 2]
```diff
@@ -0,0 +1,91 @@
...
+import { e10sProcessCount, e10sStatus } from './e10s-status';
+import Logger from './log';
+import sendEvent from './metrics';
+
+const logger = new Logger(
+  'sdk.lib.messages',
+  getMostRecentBrowserWindow().console
+);
+
+export const storeTab = uuid => {
```
Comment (fzzzy) [inline src/lib/messages.js:15]: What's the point of using an arrow function at the top level of a module, instead of just the function form? There's no need for the arrow function 'this' behavior and the function form is both shorter and way less ugly.

Comment (chuckharmston) [reply src/lib/messages.js:15]: It keeps scope clearer if you default to arrow functions unless there's an explicit reason to use function form.

File: src/lib/notify.js [hunk 3]
```diff
@@ -140,10 +141,6 @@ class Notification extends BaseElement {
   }
 
   openSurvey(surveyUrl, sentiment, sitename) {
-    if (!storage.id) {
-      storage.id = {};
-    }
-    storage.id[this.id] = tabs.activeTab;
```
Comment (fzzzy) [inline src/lib/notify.js:146]: I'm sure this is fine, but it just makes me wonder why this was necessary before but not any more. Is this supposed to be calling storeTab here too?

Comment (chuckharmston) [reply src/lib/notify.js:146]: I moved it down to `render`, a different point of the prompting lifecycle; this was the race condition this PR fixes. Sometimes the `activeTab` referenced in the former L146 ended up being the tab opened in the former L147. By moving it to the prompt initiation rather than the point where the survey is being opened in a new tab, it ensures that this race never happens.

**Review by fzzzy — APPROVED** [review]
Code looks correct, just left a few questions about style.

File: src/lib/notify.js (hunk 3 above)
Comment (fzzzy) [reply src/lib/notify.js:146]: Aha, ok, that makes sense. Thanks!

File: src/lib/messages.js (hunk 2 above)
Comment (fzzzy) [reply src/lib/messages.js:15]: How does it keep the scope clearer? I don't understand.
