### PR TITLE
Don't prompt or show pageAction in private browsing mode (closes #146).

### LINKED ISSUE #146: Heartbeat notification and Pulse URL icon are displayed in PBM
**[Affected versions]:**
-Firefox 52.0 and up
-Pulse v1.1 RC

**[Affected Platforms]:**
-All Windows
-All Mac
-All Linux

**[Prerequisites]:**
-Pulse v1.1 RC was previously installed on a clean profile.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites in Private Browsing Mode.
2. Navigate to a http or https webpage.
3. Observe the Pulse icon from the URL bar.

**[Expected result]:**
- In Private Browsing Mode the Pulse icon should not be displayed in the URL bar and also the Heartbeat notification.

**[Actual result]:**
- Heartbeat notification and Pulse URL icon are displayed in PBM.

### PR DESCRIPTION
**Pull request by chuckharmston**
Closes #146, #149.

### CODE REVIEW

File: src/lib/page-action.js [hunk 1]
```diff
@@ -38,16 +44,22 @@ export default class PageAction {
...
+            tabId,
+            popup: this.makeSurveyUrl({ sitename })
+          });
+          browser.pageAction.show(tabId);
+          browser.tabs
+            .executeScript(tabId, { code: `${PULSE_STATUS} = true;` })
+            .then();
+        });
+      } else {
+        logger.log('Not showing pageAction for ${tabId} due to protocol.');
```
Comment (lmorchard) [inline src/lib/page-action.js]: Trying this on about:* tabs, I see a log message of "Not showing pageAction for ${tabId} due to protocol." with the placeholder. Weird. 

The ultimate behavior seems correct though. So 🤷‍♂️

**Review by lmorchard — APPROVED** [review]
:+1: LGTM and works

File: src/lib/page-action.js (hunk 1 above)
Comment (chuckharmston) [reply src/lib/page-action.js]: I forgot to backtick the string. Good catch!
